### GET request to example server
GET http://localhost:8081

###

GET  http://localhost:8081/api/v1/emp

###

POST http://localhost:8081/api/v1/emp
Content-Type: application/json

{
  "name": "shiva",
  "salary": "20000"
}

###
GET  http://localhost:8081/api/v1/emp/2

###
DELETE http://localhost:8081/api/v1/emp/1

###
PUT http://localhost:8081/api/v1/emp/2
Content-Type: application/json

{
  "name": "adi",
  "salary": "90000"
}

###
GET  http://localhost:8081/api/v1/emp/search/shiva